name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request_target:
  push:
    branches:
      - main
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com

jobs:
  test-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Prepare
        id: prep
        run: |
          echo "${{ github.repository }}"
          ls -la
          cat README.md
          env
          cat $GITHUB_EVENT_PATH
  merge: # Run only on push
    runs-on: ubuntu-latest
    needs: test-action
    if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Release
        run: echo Releaseeeeeee

